### ISSUE TITLE
Rastrigin review

### ISSUE THREAD

**Issue by gabbiurlaro** [FrancescoSorrentino/Computational-Intelligence---22-23#4]
I take a look to your rastrigin soluton using evlutionary algorithms. 

I've changend from `axis=-1` to `axis=-1` because I was getting an error while drawing the figure. By the way, your solution seems correct, and reach the maximum for the sphere. This is the output(i've modified it to print also the final point):

` Solution starting from =[0.37454012 0.95071431]: solution point = [4.80484565e-07 6.70097760e-07], z =-6.798964253089707e-13
`

the final point it's closer enough to (0, 0)

**Comment by FrancescoSorrentino** [comment]
So it's normal that doesn't reach perfectly [0,0] ? Because with the classic hill climbing i can reach it easly, but with ES it struggle to get to the point

**Comment by gabbiurlaro** [comment]
I think yes. We can write to prof. Squillero, but I think that [0,0] is difficult to reach because of floating poitn representation

**Comment by FrancescoSorrentino** [comment]
Ok thanks, i'll try to change something and maybe enhancing it, i'll try to implement an adaptive algorithm
